version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro:
        patterns: ["astro", "@astrojs/*"]
      fonts:
        patterns: ["@fontsource*", "@fontsource-variable/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
